def proc = ["bash", "-c", "curl -k -I https://cgrptmcip01.cloud.cammis.ca.gov"].execute()
def output = new StringBuffer()
proc.consumeProcessOutput(output, new StringBuffer())
proc.waitFor()
println output.toString()
